=== yolly98/brain-based-weelchair-control/PreparationSystem/data/configuration_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "operative_mode": {
      "type": "string",
      "enum": ["development", "execution"]
    },
    "segregation_endpoint_IP": {
      "type": "string"
    },
    "segregation_endpoint_port": {
      "type": "integer"
    },
    "execution_endpoint_IP": {
      "type": "string"
    },
    "execution_endpoint_port": {
      "type": "integer"
    },
    "max_eeg": {
      "type": "integer"
    },
    "min_eeg": {
      "type": "integer"
    },
    "features": {
      "type": "object",
      "properties": {
        "delta_wave": {
          "type": "object",
          "properties": {
            "start_frequency": {
              "type": "number"
            },
            "end_frequency": {
              "type": "integer"
            }
          },
          "required": [
            "start_frequency",
            "end_frequency"
          ]
        },
        "theta_wave": {
          "type": "object",
          "properties": {
            "start_frequency": {
              "type": "integer"
            },
            "end_frequency": {
              "type": "integer"
            }
          },
          "required": [
            "start_frequency",
            "end_frequency"
          ]
        },
        "alpha_wave": {
          "type": "object",
          "properties": {
            "start_frequency": {
              "type": "integer"
            },
            "end_frequency": {
              "type": "integer"
            }
          },
          "required": [
            "start_frequency",
            "end_frequency"
          ]
        },
        "beta_wave": {
          "type": "object",
          "properties": {
            "start_frequency": {
              "type": "integer"
            },
            "end_frequency": {
              "type": "integer"
            }
          },
          "required": [
            "start_frequency",
            "end_frequency"
          ]
        },
        "environment": {
          "type": "object",
          "properties": {
            "indoor": {
              "type": "integer"
            },
            "outdoor": {
              "type": "integer"
            }
          },
          "required": [
            "indoor",
            "outdoor"
          ]
        }
      },
      "required": [
        "delta_wave",
        "theta_wave",
        "alpha_wave",
        "beta_wave",
        "environment"
      ]
    }
  },
  "required": [
    "operative_mode",
    "segregation_endpoint_IP",
    "segregation_endpoint_port",
    "execution_endpoint_IP",
    "execution_endpoint_port",
    "max_eeg",
    "min_eeg",
    "features"
  ]
}

=== yolly98/brain-based-weelchair-control/PreparationSystem/preparation_system_configuration.json
{
  "operative_mode": "development",
  "segregation_endpoint_IP": "172.16.0.12",
  "segregation_endpoint_port": 5000,
  "execution_endpoint_IP": "172.16.0.13",
  "execution_endpoint_port": 5000,
  "max_eeg": 15,
  "min_eeg": -15,
  "features": {
    "delta_wave": {"start_frequency": 0.5, "end_frequency": 4},
    "theta_wave": {"start_frequency": 4, "end_frequency": 8},
    "alpha_wave": {"start_frequency": 8, "end_frequency": 12},
    "beta_wave": {"start_frequency": 12, "end_frequency": 30},
    "environment": {"indoor": 0, "outdoor": 1}
  }
}
