=== yolly98/brain-based-weelchair-control/DevelopmentSystem/resources/development_system_config_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "ip_endpoint": {
      "type": "string"
    },
    "port_endpoint": {
      "type": "integer"
    },
    "operational_mode": {
      "type": "string"
    },
    "initial_number_of_generations": {
      "type": "integer"
    },
    "number_of_hidden_layers_range": {
      "type": "array",
      "items": [
        {
          "type": "integer"
        },
        {
          "type": "integer"
        }
      ]
    },
    "number_of_hidden_neurons_range": {
      "type": "array",
      "items": [
        {
          "type": "integer"
        },
        {
          "type": "integer"
        }
      ]
    },
    "validation_error_threshold": {
      "type": "number"
    },
    "test_error_threshold": {
      "type": "number"
    },
    "testing_mode": {
      "type": "boolean"
    }
  },
  "required": [
    "ip_endpoint",
    "port_endpoint",
    "operational_mode",
    "initial_number_of_generations",
    "number_of_hidden_layers_range",
    "number_of_hidden_neurons_range",
    "testing_mode"
  ]
}

=== yolly98/brain-based-weelchair-control/DevelopmentSystem/development_system_config.json
{
    "ip_endpoint": "172.16.0.13",
    "port_endpoint": 5000,
    "operational_mode": "waiting_for_dataset",
    "initial_number_of_generations": 100,
    "number_of_hidden_layers_range": [
        1,
        8
    ],
    "number_of_hidden_neurons_range": [
        1,
        64
    ],
    "validation_error_threshold": 0.3,
    "test_error_threshold": 0.3,
    "testing_mode": false
}
